const projects = [
  {
    id: 1,
    title: 'Postline',
    img: '/imgs/projects/postline.png',
    desc: 'Social Media App where users can interact with each other through posts ',
    technologies: ['React.js', 'Node.js', 'mongodb', 'Express'],
    github: 'https://github.com/DineshRout779/postline',
    live: 'https://dns-social.netlify.app/',
  },
  {
    id: 2,
    title: 'Blogbee',
    img: '/imgs/projects/blogbee.png',
    desc: 'A blogging Web Application where one can publish and read blogs 📖',
    technologies: ['React.js', 'Node.js', 'mongodb', 'Express'],
    github: 'https://github.com/DineshRout779/postline',
    live: 'https://dns-social.netlify.app/',
  },
  {
    id: 3,
    title: 'Jobify',
    img: '/imgs/projects/jobify.png',
    desc: 'App that helps companies and candidates create and apply for jobs respectively',
    technologies: ['React.js', 'Node.js', 'mongodb', 'Express'],
    github: 'https://github.com/DineshRout779/jobify',
    live: 'https://jobline.netlify.app/',
  },
  {
    id: 4,
    title: 'Trello Clone',
    img: '/imgs/projects/trello.png',
    desc: 'A clone of Trello App that helps users track their tasks and work effectively',
    technologies: ['React.js', 'Node.js', 'mongodb', 'Express'],
    github: 'https://github.com/DineshRout779/trello-clone',
    live: 'https://youshd-task.vercel.app/',
  },
  {
    id: 5,
    title: 'Notes App',
    img: '/imgs/projects/notes.png',
    desc: 'A notes app where one can add quick notes on the go. Data is saved locally.',
    technologies: ['React.js'],
    github: 'https://github.com/DineshRout779/react-notes-app',
    live: 'https://react-notes-app-rust.vercel.app/',
  },
  {
    id: 6,
    title: 'Weather App',
    img: '/imgs/projects/weather.png',
    desc: 'A weather app that tells weather details based on search query (city, state, etc)',
    technologies: ['React.js'],
    github: 'https://github.com/DineshRout779/weather-App',
    live: 'https://react-weather-app-fawn.vercel.app/',
  },
  {
    id: 7,
    title: 'Triangle Quiz',
    img: '/imgs/projects/triangle.png',
    desc: 'How much do you know about triangles 🔺? Test your skills.',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/DineshRout779/levelZero-triangleQuiz',
    live: 'https://serene-euclid-2b069d.netlify.app/',
  },
  {
    id: 8,
    title: 'URL Shortener',
    img: '/imgs/projects/url.png',
    desc: 'An app that helps to shorten URL with ease.',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/DineshRout779/URL-shortening',
    live: 'https://url-shortening-seven.vercel.app/',
  },
  {
    id: 9,
    title: 'Mini JS Projects',
    img: '/imgs/projects/mini-js.png',
    desc: 'Collection of all mini JavaScript projects',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    github: 'https://github.com/DineshRout779/Javascript-Projects',
    live: 'https://dineshrout779.github.io/Javascript-Projects/',
  },
];

export const data = { projects };
